import { PokemonType, PokemonTypeProps } from '@/types/common';

export const TOTAL_POKEMON_NUM = 1025;

export const DEFENCE_ABILITY = [
  '건조피부',
  '내열',
  '노릇노릇바디',
  '델타스트림',
  '두꺼운지방',
  '마중물',
  '복슬복슬',
  '부유',
  '불가사의부적',
  '수포',
  '저수',
  '전기엔진',
  '정화의소금',
  '축전',
  '타오르는불꽃',
  '테라셀',
  '피뢰침',
  '필터',
  '흙먹기',
  '흡수',
];

export const POKEMON_TYPE = {
  normal: {
    backgroundColor: 'bg-type-normal',
    name: '노말',
    doubleDamage: ['fighting'],
    halfDamage: [],
    noDamage: ['ghost'],
    doubleEffect: [],
    halfEffect: ['rock', 'steel'],
    noEffect: ['ghost'],
    normalEffect: [
      'normal',
      'fire',
      'water',
      'electric',
      'grass',
      'ice',
      'poison',
      'ground',
      'flying',
      'fighting',
      'psychic',
      'bug',
      'dragon',
      'dark',
      'fairy',
    ],
  },
  fighting: {
    backgroundColor: 'bg-type-fighting',
    name: '격투',
    doubleDamage: ['flying', 'psychic', 'fairy'],
    halfDamage: ['bug', 'rock', 'dark'],
    noDamage: [],
    doubleEffect: ['normal', 'ice', 'rock', 'dark', 'steel'],
    halfEffect: ['poison', 'flying', 'psychic', 'bug', 'fairy'],
    noEffect: ['ghost'],
    normalEffect: [
      'normal',
      'fire',
      'water',
      'fighting',
      'electric',
      'grass',
      'ice',
      'ground',
      'steel',
      'dragon',
    ],
  },
  flying: {
    backgroundColor: 'bg-type-flying',
    name: '비행',
    doubleDamage: ['electric', 'ice', 'rock'],
    halfDamage: ['grass', 'fighting', 'bug'],
    noDamage: ['ground'],
    doubleEffect: ['grass', 'fighting', 'bug'],
    halfEffect: ['electric', 'rock', 'steel'],
    noEffect: [],
    normalEffect: [
      'normal',
      'fire',
      'water',
      'poison',
      'flying',
      'psychic',
      'ghost',
      'dragon',
      'dark',
      'steel',
      'fairy',
    ],
  },
  poison: {
    backgroundColor: 'bg-type-poison',
    name: '독',
    doubleDamage: ['ground', 'psychic'],
    halfDamage: ['grass', 'fighting', 'poison', 'bug', 'fairy'],
    noDamage: [],
    doubleEffect: ['grass', 'fairy'],
    halfEffect: ['poison', 'ground', 'rock', 'ghost'],
    noEffect: ['steel'],
    normalEffect: [
      'normal',
      'fire',
      'water',
      'electric',
      'ice',
      'flying',
      'ghost',
      'dragon',
      'dark',
      'steel',
    ],
  },
  ground: {
    backgroundColor: 'bg-type-ground',
    name: '땅',
    doubleDamage: ['water', 'grass', 'ice'],
    halfDamage: ['poison', 'rock'],
    noDamage: ['electric'],
    doubleEffect: ['fire', 'electric', 'poison', 'rock', 'steel'],
    halfEffect: ['grass', 'bug'],
    noEffect: ['flying'],
    normalEffect: [
      'normal',
      'fire',
      'fighting',
      'ground',
      'psychic',
      'bug',
      'ghost',
      'dragon',
      'dark',
      'fairy',
    ],
  },
  rock: {
    backgroundColor: 'bg-type-rock',
    name: '바위',
    doubleDamage: ['water', 'grass', 'fighting', 'ground', 'steel'],
    halfDamage: ['normal', 'fire', 'poison', 'flying'],
    noDamage: [],
    doubleEffect: ['fire', 'ice', 'flying', 'bug'],
    halfEffect: ['fighting', 'ground', 'steel'],
    noEffect: [],
    normalEffect: ['electric', 'ice', 'dragon', 'dark', 'fairy'],
  },
  bug: {
    backgroundColor: 'bg-type-bug',
    name: '벌레',
    doubleDamage: ['fire', 'flying', 'rock'],
    halfDamage: ['grass', 'fighting', 'ground'],
    noDamage: [],
    doubleEffect: ['grass', 'psychic', 'dark'],
    halfEffect: [
      'fire',
      'fighting',
      'poison',
      'flying',
      'ghost',
      'steel',
      'fairy',
    ],
    noEffect: [],
    normalEffect: [
      'normal',
      'water',
      'electric',
      'ice',
      'poison',
      'psychic',
      'ghost',
      'dragon',
      'dark',
      'steel',
      'fairy',
    ],
  },
  ghost: {
    backgroundColor: 'bg-type-ghost',
    name: '고스트',
    doubleDamage: ['ghost', 'dark'],
    halfDamage: ['poison', 'bug'],
    noDamage: ['normal', 'fighting'],
    doubleEffect: ['ghost', 'psychic'],
    halfEffect: ['dark'],
    noEffect: ['normal'],
    normalEffect: [
      'fire',
      'water',
      'electric',
      'grass',
      'ice',
      'ground',
      'flying',
      'psychic',
      'rock',
      'dragon',
      'dark',
      'steel',
      'fairy',
    ],
  },
  steel: {
    backgroundColor: 'bg-type-steel',
    name: '강철',
    doubleDamage: ['fire', 'fighting', 'ground'],
    halfDamage: [
      'normal',
      'grass',
      'ice',
      'flying',
      'psychic',
      'bug',
      'rock',
      'dragon',
      'steel',
      'fairy',
    ],
    noDamage: ['poison'],
    doubleEffect: ['ice', 'rock', 'fairy'],
    halfEffect: ['fire', 'water', 'electric', 'steel'],
    noEffect: [],
    normalEffect: [
      'normal',
      'water',
      'electric',
      'fire',
      'poison',
      'ground',
      'flying',
      'ghost',
      'dark',
    ],
  },
  fire: {
    backgroundColor: 'bg-type-fire',
    name: '불꽃',
    doubleDamage: ['water', 'ground', 'rock'],
    halfDamage: ['fire', 'grass', 'ice', 'bug', 'steel', 'fairy'],
    noDamage: [],
    doubleEffect: ['grass', 'ice', 'bug', 'steel'],
    halfEffect: ['fire', 'water', 'rock', 'dragon'],
    noEffect: [],
    normalEffect: [
      'normal',
      'electric',
      'poison',
      'flying',
      'psychic',
      'ghost',
      'dragon',
      'dark',
    ],
  },
  water: {
    backgroundColor: 'bg-type-water',
    name: '물',
    doubleDamage: ['electric', 'grass'],
    halfDamage: ['fire', 'water', 'ice', 'steel'],
    noDamage: [],
    doubleEffect: ['fire', 'ground', 'rock'],
    halfEffect: ['water', 'grass', 'dragon'],
    noEffect: [],
    normalEffect: [
      'normal',
      'fighting',
      'poison',
      'steel',
      'electric',
      'ice',
      'ground',
      'flying',
      'bug',
      'psychic',
      'ghost',
      'dark',
      'fairy',
    ],
  },
  grass: {
    backgroundColor: 'bg-type-grass',
    name: '풀',
    doubleDamage: ['fire', 'ice', 'poison', 'flying', 'bug'],
    halfDamage: ['water', 'electric', 'grass', 'ground'],
    noDamage: [],
    doubleEffect: ['water', 'ground', 'rock'],
    halfEffect: ['fire', 'grass', 'poison', 'flying', 'bug', 'dragon', 'steel'],
    noEffect: [],
    normalEffect: [
      'normal',
      'fighting',
      'rock',
      'psychic',
      'ghost',
      'dragon',
      'dark',
      'steel',
      'fairy',
    ],
  },
  electric: {
    backgroundColor: 'bg-type-electric',
    name: '전기',
    doubleDamage: ['ground'],
    halfDamage: ['electric', 'flying', 'steel'],
    noDamage: [],
    doubleEffect: ['water', 'flying'],
    halfEffect: ['electric', 'grass', 'dragon'],
    noEffect: ['ground'],
    normalEffect: [
      'normal',
      'fire',
      'water',
      'grass',
      'ice',
      'fighting',
      'poison',
      'bug',
      'psychic',
      'ghost',
      'dragon',
      'dark',
      'fairy',
    ],
  },
  psychic: {
    backgroundColor: 'bg-type-psychic',
    name: '에스퍼',
    doubleDamage: ['bug', 'ghost', 'dark'],
    halfDamage: ['fighting', 'psychic'],
    noDamage: [],
    doubleEffect: ['fighting', 'poison'],
    halfEffect: ['psychic', 'steel'],
    noEffect: ['dark'],
    normalEffect: [
      'normal',
      'fire',
      'water',
      'electric',
      'grass',
      'poison',
      'ground',
      'flying',
      'rock',
      'steel',
      'fairy',
      'dragon',
    ],
  },
  ice: {
    backgroundColor: 'bg-type-ice',
    name: '얼음',
    doubleDamage: ['fire', 'fighting', 'rock', 'steel'],
    halfDamage: ['ice'],
    noDamage: [],
    doubleEffect: ['grass', 'ground', 'flying', 'dragon'],
    halfEffect: ['fire', 'water', 'ice', 'steel'],
    noEffect: [],
    normalEffect: [
      'normal',
      'water',
      'electric',
      'grass',
      'poison',
      'ground',
      'flying',
      'bug',
      'psychic',
      'ghost',
      'dragon',
      'dark',
      'fairy',
    ],
  },
  dragon: {
    backgroundColor: 'bg-type-dragon',
    name: '드래곤',
    doubleDamage: ['ice', 'dragon', 'fairy'],
    halfDamage: ['fire', 'water', 'electric', 'grass'],
    noDamage: [],
    doubleEffect: ['dragon'],
    halfEffect: ['steel'],
    noEffect: ['fairy'],
    normalEffect: [
      'normal',
      'fighting',
      'rock',
      'ground',
      'poison',
      'flying',
      'bug',
      'psychic',
      'ghost',
      'steel',
      'dark',
      'fairy',
    ],
  },
  dark: {
    backgroundColor: 'bg-type-dark',
    name: '악',
    doubleDamage: ['fighting', 'bug', 'fairy'],
    halfDamage: ['ghost', 'dark'],
    noDamage: ['psychic'],
    doubleEffect: ['psychic', 'ghost'],
    halfEffect: ['fighting', 'dark', 'fairy'],
    noEffect: [],
    normalEffect: [
      'normal',
      'bug',
      'fire',
      'water',
      'electric',
      'grass',
      'ice',
      'poison',
      'ground',
      'flying',
      'psychic',
      'rock',
      'dragon',
      'steel',
    ],
  },
  fairy: {
    backgroundColor: 'bg-type-fairy',
    name: '페어리',
    doubleDamage: ['poison', 'steel'],
    halfDamage: ['fighting', 'bug', 'dark'],
    noDamage: ['dragon'],
    doubleEffect: ['fighting', 'dragon', 'dark'],
    halfEffect: ['fire', 'poison', 'steel'],
    noEffect: [],
    normalEffect: [
      'normal',
      'fire',
      'water',
      'electric',
      'grass',
      'ice',
      'flying',
      'psychic',
      'ghost',
      'dragon',
      'dark',
      'steel',
    ],
  },
  stellar: {
    backgroundColor: 'bg-type-stellar',
    name: '스텔라',
    doubleDamage: [],
    halfDamage: [],
    noDamage: [],
    doubleEffect: [],
    halfEffect: [],
    noEffect: [],
    normalEffect: [],
  },
  unknown: {
    backgroundColor: 'bg-type-unknown',
    name: '???',
    doubleDamage: [],
    halfDamage: [],
    noDamage: [],
    doubleEffect: [],
    halfEffect: [],
    noEffect: [],
    normalEffect: [],
  },
};

export const POKEMON_TYPE_ARRAY: PokemonType[] = Object.keys(
  POKEMON_TYPE,
) as PokemonType[];

export const POKEMON_TYPE_ARRAY_KR: PokemonType[] = Object.keys(
  POKEMON_TYPE,
).map((key) => (POKEMON_TYPE as any)[key].name);

export const ATTACK_SPECIAL_MOVES = ['사우전드 에로우', '프리즈 드라이'];

export const ATTACK_SPECIAL_ABILITIES = ['배짱', '색안경'];
