import type { Metadata } from 'next';

import { Header } from '@/components/Header/Header';
import { Sidebar } from '@/components/Sidebar/Sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex flex-col bg-blue-10">
          <Header />
          <div className="grow flex">
            <Sidebar className="w-1/6 h-full" />
            <div className="w-full">main</div>
          </div>
        </div>
      </body>
    </html>
  );
}
