import type { Metadata } from 'next';

import { Header } from '@/components/Header/Header';
import { Sidebar } from '@/components/Sidebar/Sidebar';
import ReactQueryProviders from '@/hooks/useReactQuery';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProviders>
          <div className="min-h-screen flex flex-col ">
            <Header />
            <div className="h-full grow flex">
              <Sidebar className="w-1/5" />
              <div className="w-full">{children}</div>
            </div>
          </div>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
